backend "list all agencies" route, controller
opengovsg/askgovsg pull request #1427
Opened 2022-03-18 06:36 UTC by siuting0511

I have implemented a route to request list of all agencies from database, please comment.

2022-03-18 07:03 UTC, LoneRifle requested changes
lgtm otherwise for now.

2022-03-18 07:03 UTC, LoneRifle commented on server/src/modules/agency/agency.routes.ts
> +  router.get('/all', controller.listAllAgencies)
```suggestion
  router.get('/', controller.listAllAgencies)
```

2022-03-18 07:03 UTC, LoneRifle commented on server/src/modules/agency/agency.routes.ts
> +   * @route  GET /api/agencies/all
```suggestion
   * @route  GET /api/agencies
```

2022-03-18 07:04 UTC, LoneRifle commented
@siuting0511 - I also want to see some tests that verify your implementation. Could you help us with that please?

2022-03-18 07:36 UTC, siuting0511 commented
Specifically, what test would you like me to test the code with?

On Fri, 18 Mar 2022 at 15:04, LoneRifle ***@***.***> wrote:

> @siuting0511 <https://github.com/siuting0511> - I also want to see some
> tests that verify your implementation. Could you help us with that please?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/opengovsg/askgovsg/pull/1427#issuecomment-1072086321>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AI3BUXAZ47TZEVSOUR55DBDVAQTJBANCNFSM5RA6QJ7A>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-03-18 07:51 UTC, LoneRifle commented
> Specifically, what test would you like me to test the code with?

I would like some comprehensive unit test coverage in `agency.service.spec` and `agency.controller.spec` that verify that the implementations work as expected in both regular and error conditions, as well as integration test coverage in `agency.routes.spec` that ensures that both controller and service work when put together. You'll find this under `__tests__`.

I'll approve and run CI for your PR now, and you can see how your tests run.

2022-03-18 14:27 UTC, siuting0511 commented
ok, I will work on that.

2022-03-21 09:54 UTC, siuting0511 commented
I have added unit test for the backend agency route, controller and server, it seems like they are working well, please ignore the modified frontend code for now as they are not completed.

2022-03-21 11:03 UTC, LoneRifle approved these changes
I've reworked and force-pushed your branch so that it incorporates the backend changes that are of interest. As part of this, I've dropped the frontend changes that you said were incomplete and a work-in-progress, as I wanted to keep this PR focused on the backend changes.

A couple of points for you that I want to bring up:
- Use the latest version of Node and npm for this codebase. You might have noticed that your commit included a bunch of changes in the package lockfile as a result of you running `npm install` using an older version of npm that does not support v2 of the lockfile spec. Using a more recent version of npm would have avoided that.

- Pay close attention to, and _do not commit_ merge conflicts! These would cause your codebase to be unbuildable as git would litter your files with indicators where merge conflicts occur, expecting you to resolve them, not commit and push them into the repo.

If you wish to recover the changes you made to the frontend for a later PR, the relevant commit is e696f46.

2022-03-21 11:03 UTC, merged

2022-03-22 01:55 UTC, siuting0511 commented
Thank you for pointing them out! I will definitely keep those in mind in the future.