feat(insert-image): update insert image modal
opengovsg/askgovsg pull request #807
Opened 2021-11-17 12:26 UTC by wanlingt

## Problem

The current image upload tool is not intuitive.

Working towards #746 

## Solution

- Create a custom image component for the rich text editor
- Update design of image modal, referencing [Figma](https://www.figma.com/file/O6lxjjfn04Ow6nn2TMStpk/AskGov-Design-Master-v2?node-id=6271%3A69638)

## Before & After Screenshots

**BEFORE**:
[insert screenshot here]

**AFTER**:
[insert screenshot here]

## Tests

- Insert image using file upload
- Insert image using URL
- Try to upload an image without keying in alt text
- Inspect image, alt text should be whatever was entered

2021-11-18 03:20 UTC, LoneRifle requested changes
lgtm otherwise. Couple of thoughts:

- Due to our strict Content Security Policy, we should not allow for embedding images directly by URL, since allowing arbitrarily-hosted images might open us up to potential issues where images hosted on an untrusted host can potentially exploit end-users through browser. Image hotlinking is also not good practice since it imposes a burden on the image host.
- Consider using Chakra theming (study SearchBox as an example)

2021-11-18 03:26 UTC, wanlingt commented
> lgtm otherwise. Couple of thoughts:
> 
> * Due to our strict Content Security Policy, we should not allow for embedding images directly by URL, since allowing arbitrarily-hosted images might open us up to potential issues where images hosted on an untrusted host can potentially exploit end-users through browser. Image hotlinking is also not good practice since it imposes a burden on the image host.
> * Consider using Chakra theming (study SearchBox as an example)

For embedding images by URL, would this be mitigated by only accepting URLs from file.go.gov.sg? Or would it better to just remove the URL option completely?

2021-11-18 03:35 UTC, LoneRifle commented
> > lgtm otherwise. Couple of thoughts:
> > 
> > * Due to our strict Content Security Policy, we should not allow for embedding images directly by URL, since allowing arbitrarily-hosted images might open us up to potential issues where images hosted on an untrusted host can potentially exploit end-users through browser. Image hotlinking is also not good practice since it imposes a burden on the image host.
> > * Consider using Chakra theming (study SearchBox as an example)
> 
> For embedding images by URL, would this be mitigated by only accepting URLs from file.go.gov.sg? Or would it better to just remove the URL option completely?

That's a helpful mitigation! I would generally prefer that we host our own images though, since the trouble taken to upload a file on Go could have been spent just uploading into AskGov.

2021-11-18 03:40 UTC, wanlingt commented
> > > lgtm otherwise. Couple of thoughts:
> > > 
> > > * Due to our strict Content Security Policy, we should not allow for embedding images directly by URL, since allowing arbitrarily-hosted images might open us up to potential issues where images hosted on an untrusted host can potentially exploit end-users through browser. Image hotlinking is also not good practice since it imposes a burden on the image host.
> > > * Consider using Chakra theming (study SearchBox as an example)
> > 
> > 
> > For embedding images by URL, would this be mitigated by only accepting URLs from file.go.gov.sg? Or would it better to just remove the URL option completely?
> 
> That's a helpful mitigation! I would generally prefer that we host our own images though, since the trouble taken to upload a file on Go could have been spent just uploading into AskGov.

ok yup makes sense, unless agencies already use Go to generate image links - though I doubt this is very likely. Will hide the option for now, @khaleedah says to park it for sync discussion next week!

2021-11-18 09:24 UTC, LoneRifle approved these changes

2021-11-18 09:26 UTC, merged

2021-11-22 01:55 UTC, LinHuiqing commented
https://user-images.githubusercontent.com/37061143/142789673-91ecd363-703c-4546-8702-e7f0b10237a6.mov

Not sure if its intentional, but it's not very obvious the limits of where the user can drop their image. Might want to create an issue for this if it's not intentional.

2021-11-22 01:56 UTC, wanlingt commented
> Screen.Recording.2021-11-22.at.9.53.23.AM.mov 
> Not sure if its intentional, but it's not very obvious the limits of where the user can drop their image. Might want to create an issue for this if it's not intentional.

yeah i've noticed, thanks for spotting it too! fixing in a separate PR