refactor(landing): introduce v2 hero, simplify layout
opengovsg/askgovsg pull request #948
Opened 2021-12-14 07:22 UTC by LoneRifle

## Problem

Closes #797 

TODO - rework Desktop to be more inline with Figma designs

## Solution

- Place logo, searchbox and website link all as immediate children in
  tablet/desktop layout
- Use CSS grid to enforce positions for tablet/desktop elements
- Add a Hero component to agency page if no topic
- Inject Searchbox styles directly, adjust mobile height

## Screenshots

### Mobile

![image](https://user-images.githubusercontent.com/10572368/145951391-96daca99-3f89-4499-b8e1-774e693f81ed.png)
![image](https://user-images.githubusercontent.com/10572368/145951418-c0b98dc9-8288-4199-91e5-b20a5e788512.png)

### Tablet

![image](https://user-images.githubusercontent.com/10572368/145951007-15e0421f-7ce8-4289-abdc-8089d1dc96ac.png)
![image](https://user-images.githubusercontent.com/10572368/145951082-d7d82552-5905-4eba-860c-1bac6ef6f6f1.png)

### Desktop

![image](https://user-images.githubusercontent.com/10572368/145951291-7f7c8505-2c79-4b81-9948-d63e5f5cc571.png)
![image](https://user-images.githubusercontent.com/10572368/145951267-58281a0b-2d60-4216-9a75-7ec9bc4d6641.png)

2021-12-14 08:04 UTC, LinHuiqing commented
The margins for the hero banner are smaller than those of the questions list:

<img width="1792" alt="Screenshot 2021-12-14 at 3 59 42 PM" src="https://user-images.githubusercontent.com/37061143/145956729-dfd45178-4f8c-4193-8135-1922173c5f81.png">

However, based on the [Figma](https://www.figma.com/file/O6lxjjfn04Ow6nn2TMStpk/AskGov-Design-Master-v2?node-id=5932%3A45299), the margins for the hero banner should be the same:

<img width="776" alt="Screenshot 2021-12-14 at 4 03 30 PM" src="https://user-images.githubusercontent.com/37061143/145957348-addaed31-cecb-42fe-83ad-21cc2beead37.png">
 
Could you check the margins?

2021-12-14 08:21 UTC, wanlingt requested changes
Also, don't think the issue should be closed as there's still the Search focus behaviour to implement. Unless we create a separate issue for that?

2021-12-14 08:21 UTC, wanlingt commented on client/src/pages/HomePage/HomePage.component.tsx
> +            base: '90%',
I think this % should be slightly smaller, the hero isn't aligned with the search bar

<img width="356" alt="Screenshot 2021-12-14 at 3 45 42 PM" src="https://user-images.githubusercontent.com/56983748/145954837-eaf76b50-4088-4693-a741-ce6ab3715486.png">

2021-12-14 08:21 UTC, wanlingt commented on client/src/theme/components/Header.ts
> +      gridTemplateColumns: {
The Header in tablet view isn't aligned

![image](https://user-images.githubusercontent.com/56983748/145956799-2f9c819a-58c8-4b7b-a954-3e168c95561a.png)

vs Figma: 
![image](https://user-images.githubusercontent.com/56983748/145956683-3ed2e738-e7a0-4e61-81e7-6f55a65aba0e.png)

2021-12-14 08:22 UTC, wanlingt commented on client/src/pages/HomePage/HomePage.component.tsx
> +            base: '90%',
same comment as @LinHuiqing 's, so resolving this

2021-12-14 08:24 UTC, LoneRifle commented
> Also, don't think the issue should be closed as there's still the Search focus behaviour to implement. Unless we create a separate issue for that?

Yea, we should

2021-12-16 02:24 UTC, wanlingt commented
the changes look good, other than one last thing - the sticky search bar doesn't span the whole page for tablet

![image](https://user-images.githubusercontent.com/56983748/146296374-36645fed-5eb3-4400-ba18-fac465977188.png)

2021-12-16 02:33 UTC, LoneRifle commented
> the changes look good, other than one last thing - the sticky search bar doesn't span the whole page for tablet

Thanks for the catch! ensured that background of Header is always white.

2021-12-16 02:35 UTC, wanlingt approved these changes
lgtm!

2021-12-16 02:37 UTC, merged